---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: customer-transactions-git
spec:
  type: git
  params:
    - name: url
      value: https://github.ibm.com/clouspak4apps/customer-transactions
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: customer-transactions-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/kabanero/customer-transactions:tkn